import {test} from 'node:test';import assert from 'node:assert/strict';import {validateBrief,jsonObject,canRun,validateReview,validatePlan,turnResult} from './core.mjs';
import {cloudLimits,applyCloudResult,cloudProgress,assertNoStateEdits,cloudExport,validateEvidenceGate} from './cloud.mjs';
test('watermark respects explicit boolean selection',()=>{assert.equal(cloudLimits({watermark:false}).watermark,false);assert.equal(cloudLimits({watermark:true}).watermark,true);assert.throws(()=>cloudLimits({watermark:'false'}));assert.throws(()=>cloudLimits({watermark:0}));});
test('brief rejects unknown product and empty input',()=>{assert.throws(()=>validateBrief({}));assert.throws(()=>validateBrief({product:'Other',platform:'TikTok'}));});
test('JSON only, no ambiguous prose extraction',()=>{assert.deepEqual(jsonObject('```json\n{"score":3}\n```'),{score:3});assert.throws(()=>jsonObject('Success {"score":3}'));});
test('stages require predecessor and no concurrent execution',()=>{assert.equal(canRun({steps:{},busy:false},'research'),true);assert.equal(canRun({steps:{},busy:false},'video'),false);assert.equal(canRun({steps:{},busy:true},'research'),false);assert.equal(canRun({steps:{mockup:{status:'done'}},busy:false},'video'),true);});
test('review cannot auto-approve and scores are bounded',()=>{assert.equal(validateReview({score:5,checks:[],verdict:'approved'}).verdict,'review_required');assert.throws(()=>validateReview({score:6,checks:[]}));});
test('plan must contain real generation prompts',()=>{assert.throws(()=>validatePlan({concepts:[{},{}]}));});
test('research confidence is not promoted to a verified sales claim',()=>{const c={title:'One',print_prompt:'art',mockup_prompt:'mug',video_prompt:'5 sec'};const p=validatePlan({concepts:[c,c],research:[{title:'Blog',confidence:'high',finding:'Best seller'}]});assert.match(p.research[0].confidence,/not independently verified/);assert.equal(p.research[0].model_confidence,'high');});
test('failed review check always requires revision',()=>{assert.equal(validateReview({score:4,checks:[{name:'Text',status:'fail',evidence:'Wrong letters'}]}).verdict,'revise');});
test('oversized brief is rejected',()=>{assert.throws(()=>validateBrief({name:'x',product:'Mug',platform:'TikTok',audience:'US',brief:'a'.repeat(4001)}));});
test('unknown stage is rejected',()=>{assert.equal(canRun({steps:{},busy:false},'publish'),false);});
test('old replies cannot complete a new turn',()=>{const old=[{type:'agent.message',content:[{type:'text',text:'old'}]},{type:'session.status_idle'},{id:'new',type:'user.message'}];assert.equal(turnResult(old,'new'),null);assert.equal(turnResult([...old,{type:'agent.message',content:[{type:'text',text:'review'}]},{type:'session.status_idle'}],'new'),'review');assert.equal(turnResult(old,'missing'),null);});
test('non-finite scores and unknown check statuses are rejected',()=>{assert.throws(()=>validateReview({score:NaN,checks:[]}));assert.throws(()=>validateReview({score:4,checks:[{status:'approved'}]}));});
test('cloud limits are explicit and bounded',()=>{assert.deepEqual(cloudLimits(),{max_rounds:3,target_score:4.5,watermark:true});assert.throws(()=>cloudLimits({max_rounds:6}));assert.throws(()=>cloudLimits({target_score:NaN}));});
test('cloud results require media evidence, not just a final score',()=>{assert.throws(()=>applyCloudResult({limits:cloudLimits(),cloud:{}},{status:'completed',execution:'ma_cloud_skill',target_score:4.5,rounds:[{number:1,review:{score:5,checks:[]}}],best_round:1}));});
test('cloud progress parses only structured helper stdout',()=>{assert.deepEqual(cloudProgress([{type:'agent.tool_result',content:[{type:'text',text:'exit_code: 0\n--- stdout ---\n{"status":"waiting_video","round":1,"task":"test"}\n\n--- stderr ---\n'}]}]),{status:'waiting_video',round:1,task:'test',video_retries:0});assert.equal(cloudProgress([{type:'agent.message',content:[]}]),null);});
test('cloud progress exposes retry state',()=>{assert.deepEqual(cloudProgress([{type:'agent.tool_result',content:[{type:'text',text:'--- stdout ---\n{"status":"retrying_video","round":1,"video_retries":2}\n--- stderr ---\n'}]}]),{status:'retrying_video',round:1,task:null,video_retries:2});});
test('direct state edits are rejected even if a final manifest looks valid',()=>{assert.throws(()=>assertNoStateEdits([{type:'agent.tool_use',name:'edit',input:{file_path:'/mnt/session/creative-loop/state.json'}}]));assert.doesNotThrow(()=>assertNoStateEdits([{type:'agent.tool_use',name:'write',input:{file_path:'/mnt/session/review.json'}}]));});
test('cloud completion must come from an export tool result',()=>{const value={status:'completed',execution:'ma_cloud_skill'};const events=[{id:'call-export',type:'agent.tool_use',name:'bash',input:{command:'python3 /mnt/skills/pod-creative-loop/scripts/creative.py export'}},{type:'agent.tool_result',tool_use_id:'call-export',content:[{type:'text',text:'exit_code: 0\n--- stdout ---\n'+JSON.stringify(value)+'\n\n--- stderr ---\n'}]}];assert.deepEqual(cloudExport(events),value);assert.equal(cloudExport([{type:'agent.message',content:[{type:'text',text:JSON.stringify(value)}]}]),null);});
test('interrupted cloud turn cannot remain pending or report success',()=>{assert.throws(()=>turnResult([{type:'user.message',id:'u'},{type:'user.interrupt'},{type:'session.status_idle'}],'u'),/interrupted/);});

function evidenceRound(){
 const criteria=[{id:'delivery',description:'Requested deliverable',source_requirement:'Deliver it',required:true,priority:1,weight:1,asset_refs:['design']},{id:'style',description:'Preferred style',source_requirement:'Prefer it',required:false,priority:2,weight:1,asset_refs:['mockup','video']}];
 const report={summary:'Observed media',checks:criteria.map(c=>({id:c.id,status:'pass',score:5,evidence:'Observed',improvement:'Refine'})),uncovered_requirements:[],release_checks:[]};
 return {criteria,round:{evaluation:{response_id:'eval',report},audit:{response_id:'audit',report:{conflicts:[],uncovered_requirements:[]}},review:{score:5,checks:criteria.map(c=>({...report.checks.find(x=>x.id===c.id),name:c.description,required:c.required})),quality_gate:'passed',blocking_checks:[],uncovered_requirements:[]}}};
}
test('dynamic bridge validates arbitrary criterion IDs',()=>{const {criteria,round}=evidenceRound();assert.equal(validateEvidenceGate(round,criteria).quality_gate,'passed');});
test('creator cannot override independent failure with a pass',()=>{const {criteria,round}=evidenceRound();round.evaluation.report.checks[0].status='fail';assert.throws(()=>validateEvidenceGate(round,criteria),/differs from independent/);});
test('conflicting report requires adjudication',()=>{const {criteria,round}=evidenceRound();round.audit.report.conflicts=[{id:'delivery',reason:'Evidence contradicts pass'}];assert.throws(()=>validateEvidenceGate(round,criteria),/adjudication/);});
test('unresolved required conflict cannot pass',()=>{const {criteria,round}=evidenceRound();round.audit.report.conflicts=[{id:'delivery',reason:'Ambiguous evidence'}];round.adjudication={response_id:'judge',report:{...round.evaluation.report,resolutions:[{id:'delivery',resolved:false,reason:'Still uncertain'}]}};assert.throws(()=>validateEvidenceGate(round,criteria),/differs from independent/);round.review.checks[0].status='unverified';round.review.quality_gate='blocked';round.review.blocking_checks=['delivery'];assert.equal(validateEvidenceGate(round,criteria).quality_gate,'blocked');});
test('optional failed preference does not block required gate',()=>{const {criteria,round}=evidenceRound();round.evaluation.report.checks[1].status='fail';round.review.checks[1].status='fail';assert.equal(validateEvidenceGate(round,criteria).quality_gate,'passed');});
test('audit coverage gaps block acceptance',()=>{const {criteria,round}=evidenceRound();round.audit.report.uncovered_requirements=['Missing requirement'];assert.throws(()=>validateEvidenceGate(round,criteria),/Invalid quality gate/);round.review.quality_gate='blocked';round.review.uncovered_requirements=['Missing requirement'];assert.equal(validateEvidenceGate(round,criteria).quality_gate,'blocked');});
test('review score uses frozen criterion weights',()=>{const {criteria,round}=evidenceRound();criteria[0].weight=3;round.evaluation.report.checks[0].score=4;round.review.checks[0].score=4;round.review.score=4.5;assert.throws(()=>validateEvidenceGate(round,criteria),/weighted score/);round.review.score=4.25;assert.equal(validateEvidenceGate(round,criteria).score,4.25);});
